name: nilts_flutter_hooks
version: 1.0.1
description: nilts_flutter_hooks provides lint rules, quick fixes, and assists for Dart and Flutter projects to help you enforce best practices and avoid errors.
homepage: https://github.com/dassssshers/nilts
repository: https://github.com/dassssshers/nilts
issue_tracker: https://github.com/dassssshers/nilts/issues
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
funding:
  - https://github.com/sponsors/ronnnnn
topics:
  - lints
  - lint
  - analysis
  - code-style
  - tools

environment:
  sdk: '>=3.10.0 <4.0.0'

resolution: workspace

dependencies:
  nilts_core: ^1.0.0

  analyzer: '>=8.0.0 <9.0.0'
  analyzer_plugin: ^0.13.0
  analysis_server_plugin: ^0.3.0

dev_dependencies:
  very_good_analysis: 10.2.0

  test: 1.26.3
  analyzer_testing: 0.1.5
