name: nilts_clock
version: 0.3.1
description: nilts_clock provides lint rules, quick fixes, and assists for Dart and Flutter projects using the [clock](https://pub.dev/packages/clock) package to help you enforce best practices and prevent errors.
homepage: https://github.com/dassssshers/nilts
repository: https://github.com/dassssshers/nilts
issue_tracker: https://github.com/dassssshers/nilts/issues
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
funding:
  - https://github.com/sponsors/ronnnnn
topics:
  - lints
  - lint
  - analysis
  - code-style
  - tools

environment:
  sdk: '>=3.10.0 <4.0.0'

resolution: workspace

dependencies:
  nilts_core: ^0.4.0

  analyzer: '>=8.0.0'
  analyzer_plugin: ^0.13.0
  analysis_server_plugin: ^0.3.0

dev_dependencies:
  very_good_analysis: 10.0.0

  analyzer_testing: 0.1.7
  test: ^1.25.0
