name: nilts_example
description: A new Flutter project.
publish_to: 'none'

environment:
  sdk: '>=3.10.1 <4.0.0'
  flutter: '>=3.38.3'

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  clock: 1.1.2
  flutter_hooks: 0.21.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
