name: nilts_example
description: A new Flutter project.
publish_to: 'none'

environment:
  sdk: '>=3.10.0 <4.0.0'
  flutter: '>=3.38.1'

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  custom_lint: 0.8.1

flutter:
  uses-material-design: true
